### ISSUE TITLE
Collaborate with Team 3 about merging our branches

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#124]
We will continue to collaborate with Team 3 about the essentials within our branches and how we will go about merging them.  
The main points of this issue include:
a.  Begin discussion over Slack concerning merge
b.  Merge and resolve conflicts

**Comment by rsanchez-wsu** [comment]
@btdugas Could you expand/clarify the completion criteria?  The two previous issues had clearly stated completion criteria, but the two items you list here are somewhat vague.

**Comment by Dorkatron199** [comment]
Another thing to consider is that Team 3 has their own equivalent version of this issue. Having two issues means that you can have an issue for each team's milestone, but also creates a duplication of the issue. Creating one issue that handles the collaboration that is outside of both team's milestones means that any progress is not reflected in the teams' milestones, but eliminates the redundancy.

If you and team 3 are going to go the route of having two-issues for the collaboration, I suggest having the issues reference each other in their descriptions so that the relationship between the issues can be better documented. This can also help in both defining both issues and aid in collaboration, which is the point of the issues. Additionally, any commits and merges can reference both issues. This helps to better document the changes that are being done for both teams.

Team 5 has been supporting the single-issue method, which has been working for us functionally, but we still have an issue named "**T5-M6-I1: Refine JFile to the Projects Needs**" (#66), which we use as a hub for all of our out-of-milestone issues. This way, we only have one issue for the collaboration, but it still is reflected in our milestone. The only downside, is that issue #66 is a continuous issue, which means that it is ill-suited for use in milestones.

In any case, how to handle collaboration issues can be tricky since issues can only be part of one milestone. I hope this helps some.

**Comment by btdugas** [comment]
In conclusion:
Merged branch between team 3 and team 6
Commit: baf34a67f5cc5993874b825d0bae351089fb1917
