### ISSUE TITLE
Document Methods on Wiki

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#139]
Our branch currently has a lot of functions that are just sitting there in Eclipse. It would be useful if we had a place for everyone to view them outside of an IDE. We should document each of our methods (parameters and returns included) on the wiki. For formatting guidance, refer to the methods that I have posted under Team 1's section. Of course, feel free to improve on this design. Close this issue when all methods under the team 1 branch have their own wiki page.

**Comment by rsanchez-wsu** [comment]
A better approach might be to create an Ant target called `doc` or `javadoc` that builds all the javadocs and then we can figure out a place to publish them.  That would be more productive than having to maintain the same documentation in two places (source code and wiki).

**Comment by Dorkatron199** [comment]
@Swilloughby-github @rsanchez-wsu 
Regardless of what path this takes, it may also be beneficial to go ahead and assign the "documentation" label to this for future referencing of this issue and to make it easier to find this issue (via looking through the documentation issues). I didn't want to assign it myself, since this isn't my issue, but I thought I might make this suggestion. Even if this issue is rendered invalid, assigning the proper labels can help in organizing this issue as documentation itself.

An example of this would be that, even though this is intended for Team 1, this issue is relevant to our entire project, including me. It would be really nice if we could standardize our documentation methods, so I would most likely follow whatever route Team 1 takes so that any users looking for documentation can follow a similar process to find our documentation. The more we standardize documentation on our side, the more efficient our documentation will be for those coming after us.

Whatever route we take, how to find the documentation may be a good page for the wiki, since it might not be part of the rest of the documentation. This would, then, be what we would use the wiki for: "how-to"'s with examples and/or supplemental documentation that is independent of the Java Documentation.

I am not trying to intrude on Team 1, though, and apologize if this comment is unwarranted and/or unwanted. I just wanted to provide some input on this that I thought may be helpful.

**Comment by Swilloughby-github** [comment]
Don't worry about it. I'm not pretentious; I'm aware that there's lots I have to learn as both a coder and developer. Thanks for the advice.

**Comment by joyceje** [comment]
@rsanchez-wsu I understand your approach and I agree that we should have javadocs, but none of us know how to do this. Can you go over in class on how to do this so we can put that to testing.

**Comment by Dorkatron199** [comment]
@Swilloughby-github There's a lot more for us all to learn. No matter how experienced you are, you can always learn more. This is as true for me as well. I greatly appreciate your understanding.

With the exception of Prof. Sanchez and the outside people, we're all students here and all have more to learn.

**Comment by joyceje** [comment]
We are no longer going in this direction, and are going to implement JavaDocs
