### ISSUE TITLE
T5-M1-I5: Continuing Development

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#15]
# T5-M1-I5: Continuing Development

> <p>5) If all of the above objectives have been completed, team 5 shall begin work on the copy, cut, paste, and rename methods.</p>

<p>This issue is put in for the sole purpose of giving team 5 more work to do, should they finish everything else. When the deadline for the milestone is met, this issue is to be closed, regardless of whether it was ever reached. It is likely that team 5 will not reach this issue, but is added to cover all possible bases.</p>

<p>The methods chosen for this issue were chosen because they were deemed easiest to build. The cut method, should simply call the copy method to the clipboard and the delete method on the file after.  The delete method is expected to be difficult, but calling the method isn't.</p>

**Comment by Dorkatron199** [comment]
Brand almost completely finished JFile rather than just creating a skeleton structure. As this milestone is coming to a close, I am closing this issue. Any further development won't be part of Milestone 1, but milestone 2.

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 Did this issue get closed because it is no longer valid or did the work captured by it transition to another milestone/issue?  If it is no longer valid, please add the invalid label to the issue.  If it moved to another milestone/issue, please identify the new issue in a comment on this issue so that GitHub will link them.
