### ISSUE TITLE
Find/R Command With No Parameters Throws Exception

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#229]
Branch: Master
Package: edu.wright.cs.jfiles.server
File: JFilesServer.java

Issue:

When sending just `find` or `findr` with no parameters to the server, the server throws an array index out of bounds exception. The server is still able to accept new connections and procecss them without issue, but the connection that ran the `find` / `findr` command terminates.

Example IO:

```
Client accepted: Socket[addr=/127.0.0.1,port=51178,localport=9786]
Waiting for a client ...
Server Thread 51178 running.
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.wright.cs.jfiles.server.JFilesServer.handle(JFilesServer.java:305)
	at edu.wright.cs.jfiles.server.JFilesServerThread.run(JFilesServerThread.java:82)
```

**Comment by TremblingOdin** [comment]
Issue has been fixed and is functional on team9-dev branch.

**Comment by rsanchez-wsu** [comment]
@TremblingOdin I am guessing that by closing this issue you were referring to commit 6da581d.  Please have a look at it, because the way you handle the exceptions (i.e., you don't) is not suitable for merging to master.  Also, when closing an issue it is helpful to make sure that the commit gets associated with the issue.  The best way to accomplish that is by referencing the issue number in the commit message.  If you forget to do that, then add a comment to the issue mentioning the commit so that it can be found later.

**Comment by TremblingOdin** [comment]
@rsanchez-wsu Sorry, will fix going forward

**Comment by LoganRickert** [comment]
This issue is no longer relevant.
