### ISSUE TITLE
Clean up Team 1 branches

### ISSUE THREAD

**Issue by hbarri** [rsanchez-wsu/jfiles#243]
Review, compare, and understand all the diverged branches of team 1 - team1 branch (https://github.com/rsanchez-wsu/jfiles/tree/team1), team1-dev branch (https://github.com/rsanchez-wsu/jfiles/tree/team1-dev), and team1RMI-dev branch (https://github.com/rsanchez-wsu/jfiles/tree/team1RMI-dev). Then clean them up by assessing their state and deciding on what to do with each one.

**Comment by rsanchez-wsu** [comment]
@hbarri I think that it would make sense to make a distinction between the assessment phase and the action phase.  I think that this issue can cover the assessment phase as written.  That part will necessitate some discussion, which can take place here.  However, I think that the action phase is distinct and will one or more separate issues to properly capture the work to be done.

**Comment by rsanchez-wsu** [comment]
@hbarri Could you add a comment here that explains the reason for closing this milestone and any related issues/commits/etc.?

**Comment by hbarri** [comment]
This issue relates to issue #256 where we plan to archive and delete the team1RMI-dev branch and merge the team1 branch into the team1-dev branch. We plan to then hopefully be able to merge master into team1 in future milestones.

**Comment by rsanchez-wsu** [comment]
@hbarri I reopened this issue when I commented on it previously.  Did you intend to close it again with your reply to my comment or to leave it open?  I ask because I recall that team1RMI-dev was deleted at some point during the past week.  If #256 is the follow-on then I am OK with closing this issue, but I will leave that to you in case you are leaving it open on purpose.

**Comment by hbarri** [comment]
You're correct, issue #256 is the follow up for this issue so I will now close this.
