### ISSUE TITLE
Clean up Team 1 branches (Part 2)

### ISSUE THREAD

**Issue by hbarri** [rsanchez-wsu/jfiles#256]
After reviewing and comparing all the diverged branches of team 1 - team1 branch (https://github.com/rsanchez-wsu/jfiles/tree/team1), team1-dev branch (https://github.com/rsanchez-wsu/jfiles/tree/team1-dev), and team1RMI-dev branch (https://github.com/rsanchez-wsu/jfiles/tree/team1RMI-dev). We can now start the action phase of removing, merging, and editing branches. This issue is a continuation of a previous issue we had related to our previous milestone (issue #243). In this previous issue we had only planned to assess the state of those branches, we now plan to start the action phase in this issue.

After our assessment, we've found that the team1RMI-dev branch is obsolete and can be archived and deleted. We have also decided to merge the team1 branch into the team1-dev branch for now, to hopefully be able to merge master into that in later milestones. However, the team1-dev and team1 branches are significantly different, so we are expecting this merging portion of the issue to carry over to  our next milestone.

**Comment by rsanchez-wsu** [comment]
@hbarri This issue is clearly a continuation of an issue (I forget precisely which one) from this past week.  Please make mention of the original issue to ensure that our future selves and other developers who end up working on this project can follow everything along.  To do this, edit your initial summary and add a sentence mentioning the issue by number, and perhaps optionally provide something of an explanation of how the work has transitioned or will transition from that issue to this one.

**Comment by hbarri** [comment]
I edited the comment as you recommended.

**Comment by rsanchez-wsu** [comment]
@hbarri Thanks!

**Comment by hbarri** [comment]
Team1RMI-dev branch was successfully deleted and we compared the code between team1 and team1-dev. We plan to merge the team1 and team1-dev branches in our second milestone (https://github.com/rsanchez-wsu/jfiles/milestone/73) in issue #271.
