### ISSUE TITLE
Incorperate CSS Styling - Change basic elements of current GUI

### ISSUE THREAD

**Issue by SolidStateHero** [rsanchez-wsu/jfiles#268]
The CSS is implemented within the code, but it is only used for example purposes. Our goal is to style all of the current elements in an attractive and professional way to create a foundation for future additions to the GUI.

This is a child issue of issue #230 

This issue will be considered completed and closed when all elements of the GUI have had CSS styling rules applied to them.

**Comment by rsanchez-wsu** [comment]
@willeko999x After reading this issue I cannot tell what is actually supposed to be done.  The relationship between the current GUI, CSS, and FXML is not especially clear with regard to what change this issue is supposed to drive.  The description needs to be updated to include a clear statement of what needs to be done and it needs an end state/deliverable.

**Comment by SolidStateHero** [comment]
Due to difficulties getting the CSS to work, we still have work to do on this issue this week. However, we do know that the master branch has CSS files already implemented that should be working by default once rules are added. We will be continuing work on this on the following milestone (4).

**Comment by SolidStateHero** [comment]
See commit ef0c1bf

The css file for the BorderPane and Label has had several elements changed. It will serve as a good example on how to change future GUI elements, and makes the icons look a lot better.

**Comment by SolidStateHero** [comment]
Just to reiterate for future classes, the goal of this was to change the UI through basic CSS rules such that others could look at the CSS and understand the unique syntax for FXML
