### ISSUE TITLE
Expand on JUnit Wiki Page

### ISSUE THREAD

**Issue by cerasaurus** [rsanchez-wsu/jfiles#277]
This issue is to expand on the basic overview of JUnit testing.  

Possible additions include:
Example code
Example classes

This issues is considered closed when example code has been added for each of the Junit options including:

- [x] Test Class

- [x] Ant Test Runner

**Comment by rsanchez-wsu** [comment]
@cerasaurus this issue is very well written, but I am not sure that we will need to cover all of these options.  @jtrenton is also working on some JUnit capabilities, so I think it makes sense to communicate with him to ensure that there isn't duplication of effort.  In reality, all we need to get started is Test classes.  The Test Runner Class is provided by Ant and/or Eclipse (the Test Runner is basically what provides the `main()` method and in most cases is not something a typical developer needs to implement).  The test suite is just the collection of test classes and I don't think this project will ever have a need for parameterized tests.  Let me know if you have questions or if you think you've spotted a reason we should tackle one of the more advanced options and we can discuss it.

**Comment by cerasaurus** [comment]
@laurenceforshaw would you want to add your info for adding tests to autorun in Ant to the JUnit wiki page and then we can probably close this issue.

**Comment by ghost** [comment]
Would there be any special test classes that we can all test in-addition to what has already been done?

**Comment by markbrant621** [comment]
This issue was completed as we do have Junits up and running with several test classes, and laurence was able to get it to work with ant.
