### ISSUE TITLE
Implement send() test

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#279]
Implement a JUnit for the send command in JFilesServerThread()

**Comment by laurenceforshaw** [comment]
https://github.com/rsanchez-wsu/jfiles/commit/ec1a8eb52c1bbdb0833c0fefb4bdce917906e1b9

**Comment by mdgilene** [comment]
I don't think this issue is closed. There are a couple issues I see.

1. This isn't a JUnit test. This is just a class that starts up a socket and reads input/sends output. JUnit test classes follow very specific patterns.
2. It doesn't actually test any code related to the JFilesClient or JFilesServer, it's just testing the built in Java Sockets class
3. There are `suppresswarnings` all over the place that shouldn't be there, as @rsanchez-wsu said in class the other day `deprecation` should pretty much never be used and `resource` means you aren't correctly closing your resources/streams properly thus a potential memory leak.

**Comment by laurenceforshaw** [comment]
Are you looking at the same thing I am? The class I made is [[https://github.com/rsanchez-wsu/jfiles/tests/edu/wright/cs/jfiles/junit/StepTest.java ]]

**Comment by mdgilene** [comment]
Hmm seems as though I got mixed up, was looking at a couple different commits at the same time. The above stuff I mentioned though still applies to the files in this commit ec1a8eb52c1bbdb0833c0fefb4bdce917906e1b9.
