### ISSUE TITLE
Implement server-to-client file transfer - Research FTP and alternatives, then determine an appropriate option for the project

### ISSUE THREAD

**Issue by SolidStateHero** [rsanchez-wsu/jfiles#306]
This is a child issue of issue #289 

During our progress on the parent issue, we came up with the following links:
[html5 Doctor: Drag and Drop to automatically send to server](http://html5doctor.com/drag-and-drop-to-server/)
[Pushing Files to the Browser Using Delivery.js, Socket.IO and Node.js](http://liamkaufman.com/blog/2012/02/11/12-pushing-files-to-the-browser-using-deliveryjs-socketio-and-nodejs/)
[NPM: delivery.js](https://www.npmjs.com/package/delivery)
[NPM: scp2](https://www.npmjs.com/package/scp2)

We should look through these links and find other resources to determine whether or not FTP or an alternative will suit our needs.

**Comment by orangecraz** [comment]
I have an article that lists a number of FTP alternatives. I'll look at them and try to determine the strengths and weaknesses of each. Here is the article:

[A Closer Look at FTP Alternatives](https://www.globalscape.com/solutions/ftp-alternatives)

Here are what the article lists as options:

- Managed File Transfer (MFT)

- Trivial File Transfer Protocol (TFTP)

- Simple File Transfer Protocol (SFTP)

- SSH File Transfer Protocol (also SFTP)

- File Transfer Protocol – Secure (FTPS)

**Comment by orangecraz** [comment]
Here are the results of my research:

Simple File Transfer Protocol is considered obsolete. It is less resource intensive than FTP, but TFTP uses even less resources.

Managed File Transfer is a high cost method intended for businesses. It will probably not be useful for use here.

Trivial File Transfer Protocol is much less resource intensive than FTP, but is less secure. The article I used to find this states that it should be used over local networks, and not over the internet.

FTPS uses Transport Layer Security to make the transfer of files more secure. Control and Data connections can be handled concurrently, or independently, to ensure the best performance. It can be run implicitly through port 990 or explicitly through port 21. This would allow the user to run confidential files securely, while allowing non-confidential files to be sent faster.

SFTP uses SSH, or Secure Shell protocol, to secure an FTP connection. It is packet based, instead of text based, by sending a binary, and then a file. This ensures less data is used over the long run. It is also handled inline, meaning a separate data connection is not used. There is no secure or insecure version without a special command to shut off SSH. It can also send a greater variety of files, due to being more robust.

Here are my sources:

- [What’s the Difference? FTP, SFTP, and FTP/S](https://southrivertech.com/whats-difference-ftp-sftp-ftps/)

- [Difference Between FTP and TFTP](http://www.differencebetween.net/technology/internet/difference-between-ftp-and-tftp/)

- [File Transfer Protocol](https://en.wikipedia.org/wiki/File_Transfer_Protocol)

**Comment by dmaddalena** [comment]
Lot of great information here. My vote for protocol goes to either FTPS or TFTP. Since this project is primarily a learning experience I think that FTPS could be a very good opportunity to stretch out a bit, but I also appreciate the apparent ease of TFTP implementation. This is a small application so the lightweight nature of TFTP is appealing for that reason.

**Comment by AlexMcGillvary** [comment]
It seems like, due to the limitations of TFTP being more for local area networks and not the Internet, our decision should be between SFTP and FTPS. Both seem to be emphasize security. [This article](https://www.goanywhere.com/blog/2011/10/20/sftp-ftps-secure-ftp-transfers) seems to imply that SFTP is easier to implement; however, I have no experience implementing either so it's really just a coin flip from my perspective.

**Comment by rsanchez-wsu** [comment]
@dmaddalena @AlexMcGillvary We are not likely to be able to implement FTPS.  Personally, at this stage in the project I am not convinced that the file transfer needs to be encrypted, but if you want to continue to tackle it, please go ahead.  The reason for staying away from FTPS is that it has numerous problems similar to those associated with active FTP.  Any firewall in the mix really creates a problem.  If we want to always assume that firewalls won't be an issue, then that is fine.  However, many networks also block FTP (including FTPS, which to the network behaves just like normal FTP) for "security reasons" so I can see it being problematic for some.

**Comment by LoganRickert** [comment]
I still think IOUtils will be the best solution for this project. 

http://stackoverflow.com/questions/13555668/java-send-file-using-sockets/13555702#13555702

Here is an example outlining how to do it over a socket for both input and output using the stream objects were using: 

http://stackoverflow.com/a/18055372

**Comment by orangecraz** [comment]
SFTP already has a standard java library. It's called Jsch. Here's some sample code to show some common implementations:

https://atechblogagain.wordpress.com/2013/06/04/simple-sftp-example-in-java-with-jsch/

http://stackoverflow.com/questions/14617/how-to-retrieve-a-file-from-a-server-via-sftp

IOUtils is featured in Apache Commons. It does seem to be simpler than SFTP, but I can't seem to find any sources giving any definitive answers as to how it works. Here's the wiki page about apache commons, if anyone's interested.

https://en.wikipedia.org/wiki/Apache_Commons

**Comment by SolidStateHero** [comment]
So right now we're between IOUtils and SFTP, correct? I like the idea of just using a standard library, but I think IOUtils can be done.

Here's a quick link I nabbed on IOUtils:
https://examples.javacodegeeks.com/core-java/apache/commons/io-commons/ioutils/org-apache-commons-io-ioutils-example-3/

**Comment by orangecraz** [comment]
I found where you can download apache commons, if anyone wants to give it a shot. Here is the link:

[Apache Commons Download](http://commons.apache.org/downloads/index.html)

As far as I can tell, it does not come with apache ant, so it needs to be installed.

Thanks for the suggestion, Will.

**Comment by AlexMcGillvary** [comment]
Are we committing to a decision then for the next milestone? It seems IOUtils appears easier to implement; however, SFTP has a standard Java library. Personally I agree with @willeko999x that using a standard library might be the simpler and more consistent option, but as with our original dilemma (FTPS vs SFTP) I yield to the group leader's decision.

**Comment by LoganRickert** [comment]
Apache Commons is already a depency for the project.

**Comment by orangecraz** [comment]
If we already have Apache Commons, then I see no reason not to use IOUtils.

**Comment by SolidStateHero** [comment]
Since the verdict seems to be IOUtils, I will close this issue and update Issue #307
