### ISSUE TITLE
Implement Threads

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#46]
Program will create a thread when a command to send a file from server to client. 
This will stay open till the file is done transmitting the file.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github This issue should have a more detailed description.  Additionally, consider whether it makes sense to have the thread spawning behavior apply for other commands besides just sending a file.  Also don't forget that it may be necessary to place a limit on the number of threads that the server will spawn in order to prevent resource exhaustion.

**Comment by slyr91** [comment]
Just added thread spawning for the server. Currently it has no control so it runs indefinitely and without a max limit in number of threads spawned.
