### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by joyceje** [rsanchez-wsu/jfiles#58]
Start planning how we are going to collaborate with the Jfiles and XML groups about how these files are transferring. Work out what will be needed and appoint a collaboration lead.

**Comment by Dorkatron199** [comment]
Please feel free to join the <a href="https://ceg3120fall2016.slack.com/messages/file_api_integration/">file_api_integration</a> channel in Slack to communicate with team 5. Brand Allred (@BrandAllred)  is in charge of JFile and I (John Wintersohle; @Dorkatron199) am in charge of JFileManager. You will most likely need to speak with Brand. His primary issue for the next milestone will be to refine JFile to what other teams need, so this may be a good fit. I will also do what I can.

I would also like to let you guys know that we are also hoping to do an "openWith(Application app)" method that will undoubtedly need an XML file. Unfortunately, I have yet to actually touch the functionality of this method (that is my primary issue for this milestone), so there should be no hurry at the moment. I still, though, wanted to let your team know so that you guys can keep this in mind.

**Comment by rsanchez-wsu** [comment]
@joyceje This issue should really lay out some specifics about what needs to be done; "plan how to collaborate" is quite vague.
