### ISSUE TITLE
Remove in-class content from main wiki page

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#60]
Remove all in-class content from the team 6 main Wiki page and place it on subpages. The team 6 main page should then be updated to reflect what team 6 is focused on and what they are currently working on. Any team 6 code should also be explained on a Wiki page.

**Comment by rsanchez-wsu** [comment]
@btdugas When closing an issue like this one (wiki content editing required), please make sure to add a comment to the specific wiki edit(s) that close the issue.  That is, not the wiki page itself, but the static links from the history that show the changes made.

**Comment by btdugas** [comment]
Added new subpages to easily find client side GUI information that the team collects.
Wiki page commits:
https://github.com/rsanchez-wsu/jfiles/wiki/Team-6/_history
Subpage commits and changes:
https://github.com/rsanchez-wsu/jfiles/wiki/Team-6-Ideas/_history
https://github.com/rsanchez-wsu/jfiles/wiki/Features/_history

**Comment by rsanchez-wsu** [comment]
@btdugas FYI, if you go into the history view and check the boxes for the revision just before your changes through you last revision, then you get a diff page:

https://github.com/rsanchez-wsu/jfiles/wiki/Team-6/_compare/d21c078941acb522d27e93a641961ab270bcdde9...1d2968e4aa6a807242e3bce325b40885431f3309

That would be ideal, so that the issue captures the specific changes.  At some point in the future the changes you made for this issue will no longer be at the top of the history and trying dig them out will be a pain.
