### ISSUE TITLE
Implement basic search command

### ISSUE THREAD

**Issue by ChronoAnomaly** [rsanchez-wsu/jfiles#8]
The first step is to make a simple search command that will be used to search for a file in the current directory.

**Comment by rsanchez-wsu** [comment]
@viro101 When closing an issue, it either needs to be done via an annotation in a commit message (as I covered in class) or with a note to the issue explaining how/why the issue was closed.  If a specific commit relates to the issue but was not annotated in the commit message, then simply mention the commit's SHA1 hash in a comment on the issue and GitHub will properly link the two.

**Comment by Rotbot9k** [comment]
closed by dafbfaef287f3f0f15fd0082aa06e1a573a04792
