### ISSUE TITLE
Design Gui with team 6

### ISSUE THREAD

**Issue by matthews92** [rsanchez-wsu/jfiles#82]
This task involves deciding on a layout and general ideas for the gui. This task will be completed when a mock up gui image is created and posted to the wiki with agreed upon gui functionality.

**Comment by rsanchez-wsu** [comment]
@matthews92 Please make sure that in addition to the GUI mockup that a list or description of the agreed upon functionality is also captured.  The wiki is definitely the right place for it, but the image and criteria also need to be posted here to this issue.  That will ensure that when the issue is closed the state of the mockup and criteria are captured as they are at the time of issue closure.

**Comment by AlexDespain01** [comment]
We talked to team 6 on Thursday after class and have agreed that we should merge our branches. They already have a decent base design and GUI window running, but they don't have any files displayed in their window yet. Since ours mostly only does the displaying of files in a window, we should merge our work and collaborate together on future development.

**Comment by rsanchez-wsu** [comment]
@masters1222 I definitely think a team-3/team-6 collaboration is worthwhile.

**Comment by matthews92** [comment]
We have created a team 3-6 dev branch and have a general idea of where the GUI is going.
