### ISSUE TITLE
Java bean getters and setters

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#96]
This is a continuation of #75.  We need standard getter and setter methods in the javabean to aid in serialization.
### Completion Goal

Getter and setter methods stubbed out for all private variables and objects currently in the Jfiles class.

**Comment by rsanchez-wsu** [comment]
@bdenlinger Please note that Eclipse will do this for you automatically. Let me know before/after class on Tuesday if you would like for me to show you how this works.

**Comment by tytrip** [comment]
@bdenlinger Can I close this issue? Not sure we need an issue for creating getters/setters as this can be done via Eclipse in a matter of seconds. Additionally, are we actively working on the Java Bean? I am not aware of a Java Bean class that is created as of right now, so I'm not sure this issue is still relevant.

**Comment by bdenlinger** [comment]
@tytrip I'll close.  Still working on the bean stuff.
